import "./globals.css";
import Nav from "../components/nav";
import Footer from "../components/footer";
import HomePage from "./page";

export const metadata = {
  title: "web trang suc nu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}